kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibp-installation-test
subjects:
- kind: ServiceAccount
  name: default
  namespace: ibp-installation-test
roleRef:
  kind: ClusterRole
  name: ibp-installation-test
  apiGroup: rbac.authorization.k8s.io

